apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-app
  namespace: argocd
spec:
  project: experts-live-india
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/maitymondeep/sample-voting-service.git
    path: k8s-infra/result
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mesh-demo
